import dotenv from 'dotenv'
import path from 'path'
dotenv.config({ path: path.resolve(process.cwd(), '.env') })

console.log('SECRET:', process.env.PAYLOAD_SECRET)
console.log('DB:', process.env.DATABASE_URI)

import payload from 'payload'
import config from './payload.config'

const houses = [
  {
    name: 'Napfény 95',
    slug: 'napfeny-95',
    shortDescription: 'Kompakt, energiahatékony kis ház fiatal pároknak és kisebb családoknak.',
    area: 95,
    builtArea: 80,
    floors: 1,
    rooms: 3,
    bathrooms: 1,
    masterBathroom: false,
    wardrobe: false,
    chimney: false,
    terraceSize: 12,
    roofType: 'gable',
    wallStructure: 'poroton',
    heating: ['heat_pump'],
    cooling: ['heat_pump'],
    energyRating: 'AA',
    minPlotSize: 400,
    minPlotWidth: 14,
    priceFrom: 28000000,
    priceCategory: 'budget',
    style: ['modern'],
    category: 'small',
    featured: false,
    status: 'active',
  },
  {
    name: 'Harmónia 115',
    slug: 'harmonia-115',
    shortDescription: 'Klasszikus stílusú, praktikus elrendezésű családi ház.',
    area: 115,
    builtArea: 95,
    floors: 1,
    rooms: 4,
    bathrooms: 1,
    masterBathroom: false,
    wardrobe: true,
    chimney: true,
    terraceSize: 18,
    roofType: 'gable',
    wallStructure: 'brick',
    heating: ['gas'],
    cooling: ['ac'],
    energyRating: 'B',
    minPlotSize: 500,
    minPlotWidth: 16,
    priceFrom: 34000000,
    priceCategory: 'mid',
    style: ['classic'],
    category: 'family',
    featured: true,
    status: 'active',
  },
  {
    name: 'Otthon 128',
    slug: 'otthon-128',
    shortDescription: 'Tágas nappali, modern konyha, ideális négytagú családnak.',
    area: 128,
    builtArea: 105,
    floors: 1,
    rooms: 4,
    bathrooms: 2,
    masterBathroom: true,
    wardrobe: true,
    chimney: false,
    terraceSize: 22,
    roofType: 'hip',
    wallStructure: 'poroton',
    heating: ['heat_pump', 'solar'],
    cooling: ['heat_pump'],
    energyRating: 'AA+',
    minPlotSize: 550,
    minPlotWidth: 18,
    priceFrom: 41000000,
    priceCategory: 'mid',
    style: ['modern', 'scandinavian'],
    category: 'family',
    featured: true,
    status: 'active',
  },
  {
    name: 'Skandináv 110',
    slug: 'skandinav-110',
    shortDescription: 'Letisztult skandináv dizájn, természetes anyagok, kiváló szigetelés.',
    area: 110,
    builtArea: 90,
    floors: 1,
    rooms: 3,
    bathrooms: 2,
    masterBathroom: true,
    wardrobe: true,
    chimney: true,
    terraceSize: 20,
    roofType: 'flat',
    wallStructure: 'lightweight',
    heating: ['heat_pump'],
    cooling: ['natural'],
    energyRating: 'AA++',
    minPlotSize: 450,
    minPlotWidth: 15,
    priceFrom: 38000000,
    priceCategory: 'mid',
    style: ['scandinavian'],
    category: 'family',
    featured: false,
    status: 'active',
  },
  {
    name: 'Mediterrán 145',
    slug: 'mediterran-145',
    shortDescription: 'Déli hangulatú, tágas teraszokkal, nagy üvegfelületekkel.',
    area: 145,
    builtArea: 120,
    floors: 1,
    rooms: 5,
    bathrooms: 2,
    masterBathroom: true,
    wardrobe: true,
    chimney: false,
    terraceSize: 40,
    roofType: 'hipped',
    wallStructure: 'brick',
    heating: ['gas', 'solar'],
    cooling: ['ac'],
    energyRating: 'A+',
    minPlotSize: 650,
    minPlotWidth: 20,
    priceFrom: 52000000,
    priceCategory: 'premium',
    style: ['mediterranean'],
    category: 'large',
    featured: true,
    status: 'active',
  },
  {
    name: 'Emeletes 160',
    slug: 'emeletes-160',
    shortDescription: 'Kétszintes modern ház, különálló gyerek- és szülői szárnnyal.',
    area: 160,
    builtArea: 90,
    floors: 2,
    rooms: 5,
    bathrooms: 3,
    masterBathroom: true,
    wardrobe: true,
    chimney: true,
    terraceSize: 25,
    roofType: 'gable',
    wallStructure: 'poroton',
    heating: ['gas'],
    cooling: ['ac'],
    energyRating: 'A',
    minPlotSize: 500,
    minPlotWidth: 16,
    priceFrom: 58000000,
    priceCategory: 'premium',
    style: ['modern'],
    category: 'twostorey',
    featured: false,
    status: 'active',
  },
  {
    name: 'Rusztikus 135',
    slug: 'rusztikus-135',
    shortDescription: 'Vidéki hangulatú ház, fa burkolatokkal, kéménnyel, nagy telekre.',
    area: 135,
    builtArea: 115,
    floors: 1,
    rooms: 4,
    bathrooms: 2,
    masterBathroom: false,
    wardrobe: false,
    chimney: true,
    terraceSize: 30,
    roofType: 'gable',
    wallStructure: 'brick',
    heating: ['wood', 'gas'],
    cooling: ['natural'],
    energyRating: 'B',
    minPlotSize: 800,
    minPlotWidth: 22,
    priceFrom: 44000000,
    priceCategory: 'mid',
    style: ['rustic'],
    category: 'family',
    featured: false,
    status: 'active',
  },
  {
    name: 'Villa 220',
    slug: 'villa-220',
    shortDescription: 'Prémium villa, úszómedence-alapozással, smart home rendszerrel.',
    area: 220,
    builtArea: 160,
    floors: 2,
    rooms: 6,
    bathrooms: 4,
    masterBathroom: true,
    wardrobe: true,
    chimney: true,
    terraceSize: 60,
    roofType: 'hipped',
    wallStructure: 'brick',
    heating: ['heat_pump', 'solar'],
    cooling: ['heat_pump'],
    energyRating: 'AA+',
    minPlotSize: 1200,
    minPlotWidth: 28,
    priceFrom: 120000000,
    priceCategory: 'luxury',
    style: ['modern', 'mediterranean'],
    category: 'villa',
    featured: true,
    status: 'active',
  },
  {
    name: 'Gazdaságos 85',
    slug: 'gazdasagos-85',
    shortDescription: 'Belépőszintű, funkcionális kis ház, minimális fenntartási költséggel.',
    area: 85,
    builtArea: 72,
    floors: 1,
    rooms: 3,
    bathrooms: 1,
    masterBathroom: false,
    wardrobe: false,
    chimney: false,
    terraceSize: 8,
    roofType: 'gable',
    wallStructure: 'lightweight',
    heating: ['electric'],
    cooling: ['none'],
    energyRating: 'B',
    minPlotSize: 350,
    minPlotWidth: 12,
    priceFrom: 22000000,
    priceCategory: 'budget',
    style: ['classic'],
    category: 'small',
    featured: false,
    status: 'active',
  },
  {
    name: 'Prémium 175',
    slug: 'premium-175',
    shortDescription: 'Emelt minőségű anyagok, egyedi tervezés, teljesen személyre szabható.',
    area: 175,
    builtArea: 140,
    floors: 2,
    rooms: 5,
    bathrooms: 3,
    masterBathroom: true,
    wardrobe: true,
    chimney: false,
    terraceSize: 35,
    roofType: 'flat',
    wallStructure: 'poroton',
    heating: ['heat_pump'],
    cooling: ['heat_pump'],
    energyRating: 'AA++',
    minPlotSize: 700,
    minPlotWidth: 22,
    priceFrom: 75000000,
    priceCategory: 'premium',
    style: ['modern'],
    category: 'twostorey',
    featured: true,
    status: 'active',
  },
  {
    name: 'Természet 120',
    slug: 'termeszet-120',
    shortDescription: 'Passzívház elvek alapján tervezett, minimális energiaigényű otthon.',
    area: 120,
    builtArea: 100,
    floors: 1,
    rooms: 4,
    bathrooms: 2,
    masterBathroom: true,
    wardrobe: false,
    chimney: false,
    terraceSize: 16,
    roofType: 'gable',
    wallStructure: 'lightweight',
    heating: ['heat_pump', 'solar'],
    cooling: ['natural'],
    energyRating: 'AA++',
    minPlotSize: 500,
    minPlotWidth: 16,
    priceFrom: 46000000,
    priceCategory: 'mid',
    style: ['scandinavian', 'modern'],
    category: 'family',
    featured: false,
    status: 'active',
  },
  {
    name: 'Klasszikus 150',
    slug: 'klasszikus-150',
    shortDescription: 'Időtálló klasszikus stílus, szimmetrikus homlokzat, tágas belső terek.',
    area: 150,
    builtArea: 125,
    floors: 1,
    rooms: 5,
    bathrooms: 2,
    masterBathroom: true,
    wardrobe: true,
    chimney: true,
    terraceSize: 28,
    roofType: 'hipped',
    wallStructure: 'brick',
    heating: ['gas'],
    cooling: ['ac'],
    energyRating: 'A',
    minPlotSize: 600,
    minPlotWidth: 20,
    priceFrom: 55000000,
    priceCategory: 'premium',
    style: ['classic'],
    category: 'large',
    featured: false,
    status: 'active',
  },
]

async function seed() {
  await payload.init({ config })

  console.log('🌱 Seed indítása...')

  // Meglévő házak törlése
  const existing = await payload.find({ collection: 'houses', limit: 100 })
  for (const house of existing.docs) {
    await payload.delete({ collection: 'houses', id: house.id })
  }
  console.log('🗑️  Régi adatok törölve')

  // Új házak feltöltése
  for (const house of houses) {
    await payload.create({ collection: 'houses', data: house })
    console.log(`✅ ${house.name} létrehozva`)
  }

  console.log('🎉 Seed kész!')
  process.exit(0)
}

seed().catch((err) => {
  console.error(err)
  process.exit(1)
})